name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código #copia os arquivos do repositório para o ambiente de execução do workflow
        uses: actions/checkout@v4  

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o uv
        run: pipx install uv
      
      - name: Debug arquivos
        run: |
            pwd
            ls -la
            find . -name "pyproject.toml"

      - name: Instalar dependências
        run: uv sync --all-groups

      - name: Executar linter(check)
        run: uv run task check

      - name: Executar testes
        run: uv run task test

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}