name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Instalar o uv
        run: astral-sh/setup-uv@v6
      
      - name: Debug arquivos
        run: |
            pwd
            ls -la
            find . -name "pyproject.toml"

      - name: Instalar dependências
        run: uv sync --all-groups --frozen

      - name: Executar testes
        run: uv run task test